import Head from "next/head";
import Image from "next/image";
import CardNewProfile from '../../components/Card/CardNewProfile/CardNewProfile';
import FooterSecond from "../../components/Footer/FooterSecond/FooterSecond";
import styles from './NewProfile.module.css';

export default function NewProfile(){
  return(
    <>
      <Head>
        <title>Pijar Mahir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pijar_logo.svg" />
      </Head>
      <main className={styles.container}>
        <Image className={styles.logo} src="/pijar_logo.svg" height={80} width={80} style={{ marginLeft: "auto", marginRight: "auto" }} alt='logo' />
        <div className={styles.content}>
          <Image className={styles.ilustration} src="/new-profile.svg" width={480} height={480} alt='ilustration' />
          <CardNewProfile/>
        </div>
      </main>
      <FooterSecond />

    </>
  )
}