/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import CardDetail from "../../../components/Card/CardDetail/CardDetail";
import DescCard from "../../../components/Card/DescCard/DescCard";
import Hero from "../../../components/Hero/Hero";
import Layouts from "../../../components/Layouts/Layouts";
import styles from './Detail.module.css';

export default function index() {
  const [courseId, setCourseId] = useState('')
  const router = useRouter();
  const { id } = router.query;


  const getCourse = async()=>{
    try{
      const res = await fetch(`http://localhost:9000/api/v1/course/${id}`)
      const data = await res.json()
      setCourseId(data)
      console.log(data)
    }catch(e){
      console.log(e)
    }
  }
  useEffect(()=>{
    getCourse()
  })

  return (
    <>
      <Head>
        <title>Pijar Mahir | detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pijar_logo.svg" />
      </Head>
      <Layouts>
        <div className={styles.container}>
          <Hero />
          <div className={styles.container_content}>
            <CardDetail />
            <DescCard />
          </div>
        </div>

      </Layouts>
    </>
  )
}
