import Head from "next/head";
import CardDetail from "../../components/Card/CardDetail/CardDetail";
import DescCard from "../../components/Card/DescCard/DescCard";
import Hero from "../../components/Hero/Hero";
import Layouts from "../../components/Layouts/Layouts";
import styles from './Detail.module.css';

export default function index(){
  return(
    <>
      <Head>
        <title>Pijar Mahir | detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pijar_logo.svg" />
      </Head>
      <Layouts>
        <div className={styles.container}>
          <Hero/>
          <div className={styles.container_content}>
            <CardDetail/>
            <DescCard/>
          </div>
        </div>

      </Layouts>
   
    </>
  )
}