/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head";
import React, { useState } from "react";
import Filter from "../../components/Filter/Filter";
import Layouts from "../../components/Layouts/Layouts";
import ListCourse from "../../components/ListCourse/ListCourse";
import Sort from "../../components/Sort/Sort";
import styles from "./category.module.css";


export default function index(){

  const [isChecked, setIsChecked] = useState('')

  const handleChecked =(e)=>{
    setIsChecked(e.target.value)
    console.log(e.target.value)
  }

  return(
    <>
    <Head>
      <title>Pijar Mahir - kursus</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/pijar_logo.svg" />
    </Head>
    <div className={styles.pattern}></div>
    <Layouts>
      <Sort/>
      <div className={styles.container}>
        <div className={styles.filter}>
          {/* <Section> */}
            <Filter onRating={handleChecked}/>
          {/* </Section> */}
        </div>
        <div className={styles.content}>
          {/* <Section> */}
            <ListCourse img={'/mahirprakerja.jpg'} title={'Belajar Mengelola Usaha Budi Daya Jamur untuk Calon Pengusaha Jamur'} price={10} mitra={'cariilmu'} rating={3.3} ulasan={12}/>
            <ListCourse img={'/mahirprakerja.jpg'} title={'Belajar Mengelola Usaha Budi Daya Jamur untuk Calon Pengusaha Jamur'} price={10} mitra={'cariilmu'} rating={3.3} ulasan={12}/>
            <ListCourse img={'/mahirprakerja.jpg'} title={'Belajar Mengelola Usaha Budi Daya Jamur untuk Calon Pengusaha Jamur'} price={10} mitra={'cariilmu'} rating={3.3} ulasan={12}/>
            <ListCourse img={'/mahirprakerja.jpg'} title={'Belajar Mengelola Usaha Budi Daya Jamur untuk Calon Pengusaha Jamur'} price={10} mitra={'cariilmu'} rating={3.3} ulasan={12}/>
          {/* </Section> */}
        </div>
      </div>
    </Layouts>
    </>
  )
}