import Head from "next/head";
import Layouts from "../components/Layouts/Layouts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pijar Mahir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pijar_logo.svg" />
      </Head>

      <Layouts>
        Disini main content
      </Layouts>

      <footer></footer>
    </div>
  );
}
