import { useSession } from "next-auth/react";
import Head from "next/head";
import CardForgotPass from "../components/Card/CardForgotPass/CardForgotPass";
import Layouts from "../components/Layouts/Layouts";

export default function Home() {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>Pijar Mahir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pijar_logo.svg" />
      </Head>

      <Layouts>
        <h2>Hello {session ? `${session.user.name}` : 'world'}</h2>

        Disini main content
        <CardForgotPass />
      </Layouts>

      <footer></footer>
    </div>
  );
}
